FROM jenkins/inbound-agent:latest

USER root

RUN apt-get update && apt-get install -y --no-install-recommends python3-pip && pip3 install yamllint && apt-get clean && rm -rf /var/lib/apt/lists/*
ARG KUBEVAL_VERSION="0.16.1"
RUN curl -LO "https://www.google.com/search?q=https://github.com/instrumenta/kubeval/releases/download/%24{KUBEVAL_VERSION}/kubeval-linux-amd64.tar.gz" && tar xzf kubeval-linux-amd64.tar.gz && mv kubeval /usr/local/bin/kubeval && rm kubeval-linux-amd64.tar.gz
USER jenkins # Switch back to the jenkins user for safety
